services:
  # Main application service
  - type: web
    name: triven-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /healthcheck
    envVars:
      - key: NODE_ENV
        value: production
      - key: OLLAMA_HOST
        value: http://ollama:11434
      - key: DATABASE_URL
        fromDatabase:
          name: triven-app-db
          property: connectionString
    
  # Ollama AI service
  - type: web
    name: triven-app-ollama
    env: docker
    dockerfilePath: ./Dockerfile.ollama
    plan: standard # Ollama needs more resources
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /api/tags
    port: 11434
    # Note: Render doesn't support internal networking like Docker Compose
    # You'll need to use the external URL for the Ollama service

databases:
  - name: triven-app-db
    databaseName: trivenapp
    user: trivenapp